version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

# ---------------------
# Tried:
#     entrypoint: ./docker-entrypoint.sh
# and:
#     entrypoint: ./booking_project/docker-entrypoint.sh

# Error:
# PS D:\Django_projects\Projects2024 Django\BookingLite3> docker-compose up --build
# [+] Building 0.0s (0/0)  docker:default
# [+] Building 0.1s (4/4) FINISHED                                                                                 docker:default 
#  => [web internal] load build definition from Dockerfile                                                                   0.0s 
#  => => transferring dockerfile: 2B                                                                                         0.0s 
#  => => transferring dockerfile: 577B                                                                                       0.0s 
#  => CANCELED [frontend internal] load metadata for docker.io/library/node:14-alpine                                        0.0s 
#  => CANCELED [frontend internal] load metadata for docker.io/library/nginx:alpine                                          0.0s 
# failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
